Vagrant.configure("2") do |config|

  # Nodo 1
  config.vm.define "nodo1" do |nodo1|
    nodo1.vm.box = "hashicorp-education/ubuntu-24-04"
    nodo1.vm.hostname = "nodo1"
    nodo1.vm.network "private_network", ip: "192.168.30.22"
    nodo1.vm.synced_folder ".", "/vagrant"

    nodo1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    nodo1.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.inventory_path = "inventory.ini"
    end
  end

  # Nodo 2
  config.vm.define "nodo2" do |nodo2|
    nodo2.vm.box = "hashicorp-education/ubuntu-24-04"
    nodo2.vm.hostname = "nodo2"
    nodo2.vm.network "private_network", ip: "192.168.30.23"
    nodo2.vm.synced_folder ".", "/vagrant"

    nodo2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    
  
  
    nodo2.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.inventory_path = "inventory.ini"
      end
    end
  end

